COLOR_RED = '\033[96;1m'
COLOR_WHITE_UNDERLINE = '\033[37;4m'
COLOR_WHITE_UNDERLINE_GRAY = '\033[37;4;2m'
COLOR_END = '\033[0m'

print(f'{COLOR_RED}test{COLOR_END}')
print(f'{COLOR_WHITE_UNDERLINE}test      4{COLOR_END}')
print(f'{COLOR_WHITE_UNDERLINE_GRAY}test      12{COLOR_END}')