---
name: Code Quality checks with understand
run-name: ${{ github.actor }} is checking code quality

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Code Quality
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: read
            statuses: write # Report results
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: install understand
              run: |
                wget -nv http://builds.scitools.com/all_builds/b1160/Understand/Understand-CLI-6.5.1160-Linux-64bit.tgz
                tar -xzf Understand-CLI-6.5.1160-Linux-64bit.tgz

            - name: setup license
              run: |
                scitools/bin/linux64/und -setlicensecode ${{ secrets.UNDERSTAND_LICENSE }}
            
            - name: run und commands
              run: |
                scitools/bin/linux64/und .github/und_commands.txt
            
            - name: remove license (for some reason this throws an error)
              run: |
                scitools/bin/linux64/und -deregisterlicensecode || true

            - name: show report
              run: |
                cat htmlDir/*

            - name: show metrics
              run: |
                cat metrics.csv
