---
  name: Code Quality checks with understand
  run-name: ${{ github.actor }} is checking code quality
  
  on:
      pull_request:
          branches:
              - main
  
  jobs:
      build:
          name: Code Quality
          runs-on: ubuntu-latest
  
          permissions:
              contents: read
              packages: read
              statuses: write # Report results
          
          steps:
              - uses: actions/github-script@v6
                with:
                    script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '👋 Thanks for reporting!'
                      })
  