---
name: Code Quality checks with understand

on:
    push:
    pull_request:

jobs:
    build:
        name: Code Quality
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: read
            statuses: write # Report results
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: install understand
              run: |
                wget -nv latest.scitools.com/Understand/Understand-CLI-6.5.1181-Linux-64bit.tgz
            
            - name: extract understand
              run: |
                tar -xzf Understand-CLI-6.5.1181-Linux-64bit.tgz
            
            - name: set license
              run: |
                scitools/bin/linux64/und -setlicensecode ${{ secrets.SLACK_LICENSE }}
            
            - name: test
              run: scitools/bin/linux64/und help
                
